# Generated by Django 5.2.15 on 2026-06-17 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('host', 'Host/IP'), ('url', 'URL'), ('dominio', 'Dominio'), ('servicio', 'Servicio'), ('contenedor', 'Contenedor')], max_length=30)),
                ('valor', models.CharField(max_length=255)),
                ('entorno', models.CharField(blank=True, max_length=80)),
                ('autorizado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'valor'), name='uniq_activo_tipo_valor')],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('alcance', models.TextField()),
                ('perfil', models.CharField(choices=[('inventario', 'Inventario seguro'), ('web_basico', 'Web básico'), ('tls', 'TLS/certificados'), ('nuclei_seguro', 'Nuclei seguro'), ('greenbone', 'Greenbone infraestructura')], default='inventario', max_length=40)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('planificada', 'Planificada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='borrador', max_length=40)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220)),
                ('severidad', models.CharField(choices=[('info', 'Informativa'), ('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='info', max_length=20)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('revisado', 'Revisado'), ('falso_positivo', 'Falso positivo'), ('aceptado', 'Riesgo aceptado'), ('corregido', 'Corregido')], default='nuevo', max_length=30)),
                ('herramienta', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.TextField()),
                ('evidencia', models.TextField(blank=True)),
                ('recomendacion', models.TextField(blank=True)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='core.activo')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.auditoria')),
            ],
            options={
                'ordering': ['auditoria', 'activo', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditoria_activos', to='core.activo')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_activos', to='core.auditoria')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('auditoria', 'activo'), name='uniq_auditoria_activo')],
            },
        ),
    ]
