# Generated by Django 5.2.15 on 2026-06-17 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('tls', 'TLS / Certificados'), ('http', 'HTTP / Cabeceras'), ('dns', 'DNS'), ('infra', 'Infraestructura'), ('web', 'Aplicación web'), ('internal', 'Control interno')], default='internal', max_length=32)),
                ('engine_key', models.CharField(choices=[('manual', 'Manual / revisable'), ('noop', 'Simulado / noop'), ('future_testssl', 'Futuro testssl'), ('future_sslyze', 'Futuro SSLyze'), ('future_zap', 'Futuro ZAP'), ('future_greenbone', 'Futuro Greenbone')], default='manual', max_length=40)),
                ('tipo_activo_aplicable', models.CharField(blank=True, max_length=80)),
                ('is_enabled', models.BooleanField(default=True)),
                ('nivel_riesgo_operativo', models.CharField(choices=[('passive', 'Pasivo / seguro'), ('controlled', 'Controlado'), ('intrusive', 'Intrusivo — no permitido todavía')], default='passive', max_length=32)),
                ('requiere_autorizacion', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['categoria', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='AuditCheckPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('planned', 'Planificado'), ('ready', 'Preparado sin ejecutar'), ('blocked', 'Bloqueado'), ('omitted', 'Omitido')], default='planned', max_length=24)),
                ('motivo_bloqueo', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_plans', to='core.activo')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_plans', to='core.auditoria')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_check_plans', to=settings.AUTH_USER_MODEL)),
                ('check_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_plans', to='core.checkdefinition')),
            ],
            options={
                'ordering': ['auditoria', 'activo', 'check_definition'],
                'constraints': [models.UniqueConstraint(fields=('auditoria', 'activo', 'check_definition'), name='unique_audit_asset_check_plan')],
            },
        ),
    ]
